server:
  port: 8080

spring:
  application:
    name: "AccentureBackendChallenge"
  devtools:
    add-properties: false
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:franchise_db}
    username: ${DB_USER:franchise_user}
    password: ${DB_PASSWORD:franchise_pass}
  sql:
    init:
      mode: always
      schema-locations: >
        classpath:db/migration/V1__create_franchises_table.sql,
        classpath:db/migration/V2__create_branches_table.sql,
        classpath:db/migration/V3__create_products_table.sql

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

api:
  paths:
    franchises: /api/v1/franchises